#!/usr/bin/env bash
set -euo pipefail

key="$1"
path="data/$key"

# If the file doesn't exist, download it from the given URL.
test -e "$path" || (curl "$2" > "$path")

shasum -a256 --check <<< "$key  $path" > /dev/null

cat "$path"
